### PR TITLE
Fix blist dependency

### PR DESCRIPTION
**Pull request by Dudu197**
[Blist](https://github.com/DanielStutzbach/blist) last update was 10 years ago, and the library does not supports Python 3.9+

To allow mongolite to run on new Python versions, I'm switching the `blist` lib with `sortedcontainers`, which seems to work fine.

I've also bumped the lib version to `0.1.7`.

### CODE REVIEW

**Comment by hvuhsg** [comment]
Hi thanks!
Could you take a look at the tests please?

**Comment by hvuhsg** [comment]
I have merged your code my self because I didn't want to wait for you to fix the poetry lock issue, If you would like to be mentioned as a contributor please add a CONTRIBUTORS.md file and add yourself in it and I will approve the PR.

**Comment by hvuhsg** [comment]
Also updated pypi to the new version

**Comment by Dudu197** [comment]
Thanks!
I'm a little busy this week, but I'll do the updates soon

**Comment by Dudu197** [comment]
Hey, sorry for the delay! (tough week)

I didn't notice you already fixed the `poetry.lock` and a simple merge with main should fix that.

Since there are 0 chances, i guess running the CI should be fine and you can successfully merge after.

**Pull request merged**
